version: '3.9'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: videohub-sql-server
    platform: linux/amd64
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - videohub-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_PASSWORD: ${NUGET_PASSWORD}
    container_name: videohub-backend
    ports:
      - "5000:80"
    depends_on:
      sql-server:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql-server;Database=VideoHub;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
      Jwt__Key: "${JWT_KEY}"
      Jwt__Issuer: "http://backend:80"
      Jwt__Audience: "http://frontend:3000"
      Mux__TokenId: "${MUX_TOKEN_ID}"
      Mux__TokenSecret: "${MUX_TOKEN_SECRET}"
      Stripe__SecretKey: "${STRIPE_SECRET_KEY}"
      Stripe__WebhookSecret: "${STRIPE_WEBHOOK_SECRET}"
      Google__ClientId: "${GOOGLE_CLIENT_ID}"
      Google__ClientSecret: "${GOOGLE_CLIENT_SECRET}"
    secrets:
      - nuget_username
      - nuget_token
    networks:
      - videohub-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      args:
        NUXT_PUBLIC_API_BASE_URL: "http://backend:80"
        NUXT_PUBLIC_STRIPE_PUBLIC_KEY: "${STRIPE_PUBLIC_KEY}"
    container_name: videohub-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NUXT_PUBLIC_API_BASE_URL: "http://backend:80"
      NUXT_PUBLIC_STRIPE_PUBLIC_KEY: "${STRIPE_PUBLIC_KEY}"
    networks:
      - videohub-network
    restart: on-failure

secrets:
  nuget_username:
    external: true
  nuget_token:
    external: true

networks:
  videohub-network:
    driver: bridge

volumes:
  sql-data:
