version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build: ./backend
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__Default=Server=${DB_SERVER};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};
      - Mux__TokenId=${MUX_TOKEN_ID}
      - Mux__TokenSecret=${MUX_TOKEN_SECRET}
      - Stripe__SecretKey=${STRIPE_SECRET_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:5000

volumes:
  sql_data:
