name: VideoHub CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-backend:
    name: 🔧 Build & Test .NET Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore backend dependencies
        run: dotnet restore ./backend/VideoApp/VideoApp.csproj

      - name: Build backend
        run: dotnet build ./backend/VideoApp/VideoApp.csproj --configuration Release --no-restore

      - name: Test backend
        run: dotnet test ./backend/VideoApp.Tests/VideoApp.Tests.csproj --no-build --configuration Release

      - name: Publish backend
        run: dotnet publish ./backend/VideoApp/VideoApp.csproj --configuration Release --output ./backend-publish

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-publish
          path: ./backend-publish

  build-frontend:
    name: 🧪 Build Nuxt Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  deploy-backend:
    name: 🚀 Deploy to Azure App Service
    needs: build-backend
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ steps.deploy.outputs.webapp-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-publish
          path: ./backend-publish

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: videohub-app
          slot-name: production
          package: ./backend-publish
