name: .NET CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/VideoApp.csproj

      - name: Build
        run: dotnet build ./backend/VideoApp.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./VideoApp.Tests/VideoApp.Tests.csproj --no-build --configuration Release

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-publish
          path: ./backend/bin/Release/net9.0/publish/