name: .NET CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/VideoApp/VideoApp.csproj

      - name: Build backend
        run: dotnet build ./backend/VideoApp/VideoApp.csproj --configuration Release --no-restore

      - name: Test backend
        run: dotnet test ./backend/VideoApp.Tests/VideoApp.Tests.csproj --no-build --configuration Release

      - name: Publish backend
        run: dotnet publish ./backend/VideoApp/VideoApp.csproj --configuration Release --output ./publish

      - name: Upload publish folder
        uses: actions/upload-artifact@v4
        with:
          name: videoapp-backend-publish
          path: ./publish
